-- SQLite
$sqlite3 db.db

CREATE TABLE MYTABLE(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    TODO TEXT
);

SELECT * FROM MYTABLE

DROP TABLE MYTABLE

INSERT INTO MYTABLE (TODO) VALUES ('TEST')